"""
This module contains data with wp codes
needs for wikipedia scraper to scrape not only english pages
"""
WP_CODES = {
			'England' : 'en',
			'France' : 'fr',
			'Germany' : 'de',
			'Spain' : 'es',
			'Japan' : 'ja',
			'Russia' : 'ru',
			'Portugal' : 'pt',
			'China' : 'zh',
			'Italy' : 'it',
			'Iran' : 'fa',
			'Arabia' : 'ar',
			'Poland' : 'pl',
			'Ukraine' : 'uk',
			'Netherlands' : 'nl',
			'Turkey' : 'tr',
			'Israel' : 'he',
			'Indonesia' : 'id',
			'Czech Republic' : 'cs',
			'Sweden' : 'sv',
			'Vietnam' : 'vi',
			'Finland' : 'fi',
			'Hungary' : 'hu',
			'Korea' : 'ko',
			'India' : 'hi',
			'Uzbekistan' : 'uz',
			'Catalonia' : 'ca',
			'Norway' : 'no',
			'Thailand' : 'th',
			'Bangladesh' : 'bn',
			'Romania' : 'ro',
			'Greece' : 'el',
			'Serbia' : 'sr',
			'Azerbaijan' : 'az',
			'Denmark' : 'da',
			'Estonia' : 'et',
			'Bulgaria' : 'bg',
			'Basque Country' : 'eu',
			'Slovakia' : 'sk',
			'Malaysia' : 'ms',
			'Croatia' : 'hr',
			'Armenia' : 'hy',
			'Tamil Nadu' : 'ta',
			'Lithuania' : 'lt',
			'Slovenia' : 'sl',
			'Kazakhstan' : 'kk',
			'Belarus' : 'be',
			'Esperanto' : 'eo',
			'Pakistan' : 'ur',
			'Canton (Guangzhou)' : 'zh-yue',
			'Albania' : 'sq',
			'Latvia' : 'lv',
			'Galicia' : 'gl',
			'Karnataka' : 'kn',
			'Georgia' : 'ka',
			'Kerala' : 'ml',
			'Macedonia' : 'mk',
			'Maharashtra' : 'mr',
			'Telangana' : 'te',
			'Egypt' : 'arz',
			'Tanzania' : 'sw',
			'South Africa' : 'en',
			'Iceland' : 'is',
			'Norway' : 'nn',
}

WEBSITE = {
			'England' : 'Website',
			'France' : 'Site web',
			'Germany' : 'Website',
			'Spain' : 'Sitio web',
			'Japan' : '外部リンク',
			'Russia' : 'Сайт',
			'Portugal' : 'Website',
			'China' : '网站',
			'Italy' : 'Sito web',
			'Iran' : 'وبگاه',
			'Arabia' : 'موقع الويب',
			'Netherlands' : 'Website',
			'Turkey' : 'Web sitesi',
			'Indonesia' : 'Situs web',
			'Czech Republic' : 'Oficiální web',
			'Sweden' : 'Webbplats',
			'Vietnam' : 'Số nhân viên',
			'Finland' : 'Kotisivu',
			'Korea' : '웹사이트',
			'India' : '웹사이트',
			'Uzbekistan' : 'Vebsayti',
			'Catalonia' : 'Lloc web',
			'Norway' : 'Nettsted',
			'Thailand' : 'เว็บไซต์',
			'Bangladesh' : 'ওয়েবসাইট',
			'Romania' : 'ro',
			'Greece' : 'el',
			'Serbia' : 'sr',
			'Azerbaijan' : 'az',
			'Denmark' : 'da',
			'Estonia' : 'et',
			'Bulgaria' : 'bg',
			'Basque Country' : 'eu',
			'Slovakia' : 'sk',
			'Malaysia' : 'ms',
			'Croatia' : 'hr',
			'Armenia' : 'hy',
			'Tamil Nadu' : 'ta',
			'Lithuania' : 'lt',
			'Slovenia' : 'sl',
			'Kazakhstan' : 'kk',
			'Belarus' : 'be',
			'Esperanto' : 'eo',
			'Pakistan' : 'ur',
			'Canton (Guangzhou)' : 'zh-yue',
			'Albania' : 'sq',
			'Latvia' : 'lv',
			'Galicia' : 'gl',
			'Karnataka' : 'kn',
			'Georgia' : 'ka',
			'Kerala' : 'ml',
			'Macedonia' : 'mk',
			'Maharashtra' : 'mr',
			'Telangana' : 'te',
			'Egypt' : 'arz',
			'Tanzania' : 'sw',
			'South Africa' : 'en',
			'Iceland' : 'is',
			'Norway' : 'nn',
            'Switzerland' : 'en',
            'Australia' : 'en',
            'Canada' : 'en',
            'United Kingdom' : 'en'
}